config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :homes
root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  has_many :homes, dependent: :destroy
  validates :image, presence: true
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :fullname, presence: true, length: { minimum: 6, maximum: 50 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  def index
    @homes = Home.all
  end

  def show
  end

  def new
    @home = Home.new
  end

  def create
    if @home = Home.create(home_params)
      flash[:success] = "Your post has been created!"
      redirect_to homes_path
    else
      flash.now[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @home.update(home_params)
      flash[:success] = "Post updated."
      redirect_to homes_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    @home.destroy
    redirect_to homes_path
  end

  private

  def home_params
    params.require(:home).permit(:image, :title, :location, :about, :price)
  end

  def set_home
    @home = Home.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :fullname, :phone, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :fullname, :phone, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<div class="form-wrapper">
  <%= simple_form_for @home, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
    <%= f.input :image %>
    </div>
    <div class="form-group text-left">
      <%= f.input :title %>
    </div>
    <div class="form-group text-left">
      <%= f.input :location %>
    </div>
    <div class="form-group text-left">
      <%= f.input :about %>
    </div>
    <div class="form-group text-left">
      <%= f.input :price %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/homes/edit.html.erb
<div class="coverImage" style="background-image: url('<%= @home.image.url %>');" aria-hidden="true"></div>
<%= render 'form' %>
<div class="text-center edit-links">
  <%= link_to "Delete home", home_path(@home), method: :delete, data: { confirm: "Are you sure you want to delete this home?" } %>
  <%= link_to "cancel", homes_path %>
</div>

app/views/homes/index.html.erb
<div class="posts-wrapper row">
  <% @homes.each do |home| %>
      <div class="col-md-6 box">
      <div class="post">
        <div class="post-head">
          <div class="name">
            Host
          </div>
        </div>
        <div class="image center-block">
          <%= link_to (image_tag home.image.url(:medium)), home_path(home) %>
        </div>
        <p class="caption">
          <h1><%= home.title %></h1><br>
          <%= home.location %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/homes/new.html.erb
<%= render 'form' %>
<div class="text-center edit-links">
  <%= link_to "Cancel", homes_path %>
  <br/>
</div>

app/views/homes/show.html.erb
<div class="homes-wrapper row">
  <div class="home">
    <div class="coverImage" style="background-image: url('<%= @home.image.url %>');" aria-hidden="true"></div>
    <p class="caption">
      <%= @home.title %><br>
      <%= @home.location %><br>
      <%= @home.about %><br>
      <%= @home.price %>
    </p>
    <div class="text-center">
      <%= link_to "Cancel", homes_path %>
      <%= link_to "Edit Home", edit_home_path(@home) %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
  <div class="navbar-header">
    <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand">
      <%= link_to "FireBnb", root_path %>
    </div>
  </div>
  <div class="collapse navbar-collapse" id="bs-navbar-collapse-3">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to "Post", new_home_path %>
        </li>
        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Register", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <meta charset="utf-8"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <title>FireBnb</title>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert] %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>